/*
 * Trabalho APS
 */
package apscliente;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author TW
 */
public class TelaInicial extends javax.swing.JFrame {

    private Cadastro telaCadastro = new Cadastro();
    private Login telaLogin = new Login();
    private String ipServer = null;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        Logar = new javax.swing.JButton();
        Cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ambiente de Comunicação");
        setResizable(false);

        Bg.setBackground(new java.awt.Color(0, 0, 153));

        titulo.setHorizontalAlignment(SwingConstants.CENTER);
        titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("INICIO");

        Logar.setBackground(new java.awt.Color(255, 255, 255));
        Logar.setForeground(new java.awt.Color(0, 0, 0));
        Logar.setText("Login");
        Logar.setAlignmentY(0.0F);
        Logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogarActionPerformed(evt);
            }
        });

        Cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        Cadastrar.setForeground(new java.awt.Color(0, 0, 0));
        Cadastrar.setText("Cadastro");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BgLayout = new javax.swing.GroupLayout(Bg);
        Bg.setLayout(BgLayout);
        BgLayout.setHorizontalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
            .addGroup(BgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        BgLayout.setVerticalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logar)
                    .addComponent(Cadastrar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        try {
            /*CapturaWebCam tst = new CapturaWebCam();
            tst.setVisible(true);
            tst.setTipo("Cadastro");*/
            telaCadastro.setConexao(getConexao());
            telaCadastro.setVisible(true);
            telaCadastro.setInicial(this);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possivel conectar ao servidor. \r\n"
                    + "Verifique se o IP foi digitado corretamente\r\n"
                    + "E o servidor está ativo!");
            this.ipServer = null;
        }catch (Exception ex) {
            //Faz nada 
        }
    }//GEN-LAST:event_CadastrarActionPerformed

    private void LogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogarActionPerformed
        try {
            telaLogin.setConexao(getConexao());
            telaLogin.setVisible(true);
            telaLogin.setInicial(this);
            telaLogin.setIp(this.ipServer);
            this.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possivel conectar ao servidor. \r\n"
                    + "Verifique se o IP foi digitado corretamente\r\n"
                    + "E o servidor está ativo!");
            this.ipServer = null;
        } catch (Exception ex) {
            //Faz nada 
        }
       
    }//GEN-LAST:event_LogarActionPerformed
    private Socket getConexao() throws IOException, Exception {
        if (this.ipServer == null) {
            this.ipServer = JOptionPane.showInputDialog(this, "Insira o IP do Servidor");
        }
        //Se chegar aqui e ipServer continular null, usuario fechou o OptionPane sem inserir nada
        if (this.ipServer == null) {
            throw new Exception("Usuario fechou JOptionPane");
        }
        //Tenta efetuar a conexão
        Socket conexao = new Socket(this.ipServer,1250);
        return conexao;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Logar;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
